-- M A S T E R - C H I E F --
-----------------------------

--- Paramètres ---
OPEN_BAGS = true
debug_mode = false -- Remplacer "false" par "true" pour activer le mode Debug ou inversement pour le desactiver
del_mode = false -- Remplacer "false" par "true" pour activer la supression automatique ou inversement pour la desactiver
if debug_mode then
	global:printMessage("Mode Debug : ON (pour le desactiver: mettre 'debug_mode' sur 'false')." )
else
	global:printMessage("Mode Debug : OFF (pour l'activer: mettre 'debug_mode' sur 'true')." )
end
if del_mode then
	global:printMessage("Mode Supression Auto : ON (pour la desactiver: mettre 'del_mode' sur 'false')." )
	AUTO_DELETE = { 289, 400, 533, 401, 423, 532, 405, 425 }
else
	global:printMessage("Mode Supression Auto : OFF (pour l'activer: mettre 'del_mode' sur 'true')." )
end
global:printError("Script realise par Master Chief - (RETOUR EN BANQUE CONSEILLE : 90%)" )
global:printSuccess("[STATS] Pods : " .. inventory:podsP() .. "%" )
------------------

function move()
	if debug_mode then
		global:printMessage("[DEBUG] Map : [" .. map:currentMap() .. "] - " .. job:name(28) .. " : " .. job:level(28) .. " - Pods : " .. inventory:podsP() .. "%" )
	end
	if (job:level(28) < 20) then
		GATHER = {38}
		return {
			{map = "2885641", path = "424"}, --Interieur banque Bonta vers Sortie--
			{map = "-29,-54", path = "bottom"},
			{map = "-29,-53", path = "bottom"},
			{map = "-29,-52", path = "bottom"},
			{map = "-29,-51", path = "bottom"},
			{map = "-29,-50", path = "bottom"},
			{map = "-29,-49", path = "bottom"},
			{map = "-29,-48", path = "bottom"},
			{map = "-29,-47", path = "bottom"},
			{map = "-29,-46", path = "bottom"},
			{map = "-31,-54", path = "right"},
			{map = "-30,-54", path = "right"},
			{map = "-28,-45", path = "bottom", gather = true},
			{map = "-28,-44", path = "right", gather = true},
			{map = "-27,-43", path = "right", gather = true},
			{map = "-26,-43", path = "bottom", gather = true},
			{map = "-24,-41", path = "right", gather = true},
			{map = "-23,-40", path = "bottom", gather = true},
			{map = "-24,-39", path = "top", gather = true},
			{map = "-24,-40", path = "left", gather = true},
			{map = "-25,-40", path = "bottom", gather = true},
			{map = "-26,-39", path = "left", gather = true},
			{map = "-26,-38", path = "top", gather = true},
			{map = "-29,-40", path = "right", gather = true},
			{map = "-29,-39", path = "top"},
			{map = "-27,-39", path = "left"},
			{map = "-28,-39", path = "left"},
			{map = "-28,-41", path = "top"},
			{map = "-28,-42", path = "top"},
			{map = "-28,-43", path = "left"},
			{map = "-29,-44", path = "top"},
			{map = "-29,-43", path = "top"},
			{map = "-29,-45", path = "right"},
			{map = "-27,-44", path = "bottom"},
			{map = "-26,-42", path = "right", gather = true},
			{map = "-25,-42", path = "bottom"},
			{map = "-25,-41", path = "right"},
			{map = "-23,-41", path = "bottom"},
			{map = "-23,-39", path = "left"},
			{map = "-25,-39", path = "bottom"},
			{map = "-25,-38", path = "left"},
			{map = "-28,-40", path = "top"},
			{map = "-32,-56", path = "right"},
			{map = "-31,-56", path = "bottom"},
			{map = "-31,-55", path = "bottom"},
		}
	elseif (job:level(28) >= 20) and (job:level(28) < 40) then
		GATHER = {38, 43}
		return {
			{map = "2885641", path = "424"}, --Interieur banque Bonta vers Sortie--
			{map = "-32,-56", path = "bottom"},
			{map = "-32,-55", path = "bottom"},
			{map = "-32,-54", path = "right"},
			{map = "-31,-54", path = "right"},
			{map = "-30,-54", path = "right"},
			{map = "-29,-54", path = "bottom"},
			{map = "-29,-53", path = "bottom"},
			{map = "-29,-51", path = "bottom"},
			{map = "-29,-52", path = "bottom"},
			{map = "-29,-49", path = "bottom"},
			{map = "-29,-50", path = "bottom"},
			{map = "-29,-47", path = "bottom"},
			{map = "-29,-48", path = "bottom"},
			{map = "-29,-45", path = "right"},
			{map = "-29,-46", path = "bottom"},
			{map = "-28,-45", path = "bottom", gather = true},
			{map = "-28,-44", path = "right", gather = true},
			{map = "-27,-44", path = "bottom", gather = true},
			{map = "-27,-43", path = "right", gather = true},
			{map = "-25,-44", path = "bottom", gather = true},
			{map = "-25,-43", path = "right", gather = true},
			{map = "-22,-43", path = "bottom", gather = true},
			{map = "-23,-42", path = "left", gather = true},
			{map = "-24,-42", path = "bottom", gather = true},
			{map = "-24,-41", path = "right", gather = true},
			{map = "-23,-40", path = "bottom", gather = true},
			{map = "-24,-39", path = "top", gather = true},
			{map = "-24,-40", path = "left", gather = true},
			{map = "-25,-40", path = "bottom", gather = true},
			{map = "-26,-39", path = "bottom", gather = true},
			{map = "-26,-38", path = "bottom", gather = true},
			{map = "-26,-37", path = "left", gather = true},
			{map = "-29,-37", path = "top", gather = true},
			{map = "-29,-38", path = "top", gather = true},
			{map = "-29,-39", path = "right", gather = true},
			{map = "-28,-39", path = "right", gather = true},
			{map = "-27,-40", path = "top", gather = true},
			{map = "-27,-42", path = "left", gather = true},
			{map = "-26,-43", path = "top"},
			{map = "-26,-44", path = "right"},
			{map = "-24,-43", path = "right"},
			{map = "-23,-43", path = "right"},
			{map = "-22,-42", path = "left"},
			{map = "-23,-41", path = "bottom"},
			{map = "-23,-39", path = "left"},
			{map = "-25,-39", path = "left"},
			{map = "-27,-37", path = "left"},
			{map = "-28,-37", path = "left"},
			{map = "-27,-39", path = "top"},
			{map = "-27,-41", path = "top"},
			{map = "-28,-42", path = "left"},
			{map = "-29,-42", path = "top"},
			{map = "-29,-43", path = "top"},
			{map = "-29,-44", path = "top"},
			{map = "-25,-37", path = "left"},
			{map = "-25,-38", path = "left"},
			{map = "-24,-37", path = "left"},
			{map = "-24,-38", path = "left"},
			{map = "-23,-37", path = "left"},
			{map = "-23,-38", path = "left"},
			{map = "-22,-37", path = "left"},
			{map = "-22,-38", path = "left"},
			{map = "-21,-37", path = "left"},
			{map = "-21,-38", path = "left"},
			{map = "-21,-39", path = "left"},
			{map = "-22,-39", path = "left"},
			{map = "-22,-40", path = "left"},
			{map = "-22,-41", path = "left"},
			{map = "-21,-41", path = "left"},
			{map = "-21,-40", path = "left"},
			{map = "-21,-42", path = "left"},
			{map = "-21,-43", path = "left"},
			{map = "-21,-44", path = "left"},
			{map = "-22,-44", path = "left"},
			{map = "-23,-44", path = "left"},
			{map = "-24,-44", path = "left"},
			{map = "-22,-45", path = "left"},
			{map = "-21,-45", path = "left"},
			{map = "-23,-45", path = "left"},
			{map = "-24,-45", path = "left"},
			{map = "-25,-45", path = "left"},
			{map = "-27,-45", path = "left"},
			{map = "-26,-45", path = "left"},
			{map = "-25,-42", path = "left"},
			{map = "-26,-42", path = "left"},
			{map = "-25,-41", path = "left"},
			{map = "-26,-41", path = "left"},
			{map = "-26,-40", path = "left"},
			{map = "-27,-38", path = "left"},
			{map = "-28,-38", path = "left"},
			{map = "-29,-40", path = "right"},
			{map = "-28,-40", path = "right"},
			{map = "-28,-41", path = "right"},
			{map = "-29,-41", path = "right"},
			{map = "-30,-37", path = "right"},
			{map = "-30,-38", path = "right"},
			{map = "-30,-39", path = "right"},
			{map = "-30,-40", path = "right"},
			{map = "-30,-41", path = "right"},
			{map = "-30,-42", path = "right"},
			{map = "-30,-43", path = "right"},
			{map = "-30,-44", path = "right"},
			{map = "-30,-45", path = "right"},
		}
	elseif (job:level(28) >= 40) and (job:level(28) < 60) then
		GATHER = {38, 43, 45}
		return {
			{map = "2885641", path = "424"}, --Interieur banque Bonta vers Sortie--
			{map = "-32,-55", path = "bottom"},
			{map = "-32,-56", path = "bottom"},
			{map = "-32,-54", path = "right"},
			{map = "-30,-54", path = "right"},
			{map = "-31,-54", path = "right"},
			{map = "-29,-54", path = "bottom"},
			{map = "-29,-53", path = "bottom"},
			{map = "-29,-52", path = "bottom"},
			{map = "-29,-51", path = "bottom"},
			{map = "-29,-50", path = "bottom"},
			{map = "-29,-49", path = "bottom"},
			{map = "-29,-48", path = "bottom"},
			{map = "-29,-47", path = "bottom"},
			{map = "-29,-46", path = "bottom"},
			{map = "-29,-45", path = "right"},
			{map = "-28,-45", path = "bottom", gather = true},
			{map = "-27,-44", path = "bottom", gather = true},
			{map = "-25,-44", path = "bottom", gather = true},
			{map = "-28,-44", path = "right", gather = true},
			{map = "-27,-43", path = "right", gather = true},
			{map = "-25,-43", path = "right", gather = true},
			{map = "-26,-43", path = "top", gather = true},
			{map = "-22,-43", path = "bottom", gather = true},
			{map = "-23,-42", path = "bottom", gather = true},
			{map = "-24,-41", path = "bottom", gather = true},
			{map = "-23,-40", path = "bottom", gather = true},
			{map = "-24,-39", path = "left", gather = true},
			{map = "-25,-40", path = "top", gather = true},
			{map = "-25,-42", path = "left", gather = true},
			{map = "-26,-42", path = "bottom", gather = true},
			{map = "-26,-41", path = "bottom", gather = true},
			{map = "-26,-39", path = "bottom", gather = true},
			{map = "-26,-38", path = "bottom", gather = true},
			{map = "-26,-37", path = "left", gather = true},
			{map = "-27,-38", path = "left", gather = true},
			{map = "-28,-38", path = "bottom", gather = true},
			{map = "-28,-37", path = "left", gather = true},
			{map = "-29,-37", path = "top", gather = true},
			{map = "-29,-38", path = "top", gather = true},
			{map = "-27,-40", path = "top", gather = true},
			{map = "-26,-44", path = "right"},
			{map = "-24,-43", path = "right"},
			{map = "-23,-43", path = "right"},
			{map = "-22,-42", path = "left"},
			{map = "-23,-41", path = "left"},
			{map = "-23,-39", path = "left"},
			{map = "-25,-39", path = "top"},
			{map = "-25,-41", path = "top"},
			{map = "-26,-40", path = "bottom"},
			{map = "-27,-37", path = "top"},
			{map = "-27,-39", path = "top"},
			{map = "-27,-41", path = "top"},
			{map = "-27,-42", path = "left"},
			{map = "-28,-42", path = "left"},
			{map = "-29,-43", path = "top"},
			{map = "-29,-44", path = "top"},
			{map = "-29,-42", path = "top"},
			{map = "-30,-45", path = "right"},
			{map = "-30,-44", path = "right"},
			{map = "-30,-43", path = "right"},
			{map = "-30,-42", path = "right"},
			{map = "-30,-41", path = "right"},
			{map = "-28,-41", path = "right"},
			{map = "-29,-40", path = "right"},
			{map = "-29,-41", path = "right"},
			{map = "-28,-40", path = "right"},
			{map = "-30,-40", path = "right"},
			{map = "-30,-39", path = "right"},
			{map = "-24,-40", path = "right", gather = true},
			{map = "-29,-39", path = "right", gather = true},
			{map = "-28,-39", path = "right", gather = true},
			{map = "-28,-43", path = "right"},
			{map = "-30,-38", path = "right"},
			{map = "-30,-37", path = "right"},
			{map = "-21,-44", path = "left"},
			{map = "-22,-44", path = "left"},
			{map = "-23,-44", path = "left"},
			{map = "-24,-44", path = "left"},
			{map = "-21,-43", path = "left"},
			{map = "-21,-42", path = "left"},
			{map = "-21,-41", path = "left"},
			{map = "-21,-39", path = "left"},
			{map = "-21,-40", path = "left"},
			{map = "-21,-38", path = "left"},
			{map = "-21,-37", path = "left"},
			{map = "-22,-37", path = "left"},
			{map = "-22,-38", path = "left"},
			{map = "-22,-39", path = "left"},
			{map = "-22,-40", path = "left"},
			{map = "-22,-41", path = "left"},
			{map = "-23,-37", path = "left"},
			{map = "-23,-38", path = "left"},
			{map = "-24,-38", path = "left"},
			{map = "-24,-37", path = "left"},
			{map = "-25,-37", path = "left"},
			{map = "-25,-38", path = "left"},
			{map = "-24,-42", path = "left"},
			{map = "-21,-45", path = "left"},
			{map = "-22,-45", path = "left"},
			{map = "-23,-45", path = "left"},
			{map = "-25,-45", path = "left"},
			{map = "-24,-45", path = "left"},
			{map = "-26,-45", path = "left"},
			{map = "-27,-45", path = "left"},
		}
	elseif (job:level(28) >= 60) and (job:level(28) < 80) then
		GATHER = {39, 43, 45}
		return {
			{map = "2885641", path = "424"}, --Interieur banque Bonta vers Sortie--
			{map = "-32,-56", path = "bottom"},
			{map = "-32,-55", path = "bottom"},
			{map = "-32,-54", path = "right"},
			{map = "-31,-54", path = "right"},
			{map = "-30,-54", path = "right"},
			{map = "-29,-54", path = "bottom"},
			{map = "-29,-53", path = "bottom"},
			{map = "-29,-52", path = "bottom"},
			{map = "-29,-51", path = "bottom"},
			{map = "-29,-50", path = "bottom"},
			{map = "-29,-49", path = "bottom"},
			{map = "-29,-48", path = "bottom"},
			{map = "-29,-47", path = "bottom"},
			{map = "-29,-46", path = "bottom"},
			{map = "-29,-45", path = "right"},
			{map = "-28,-45", path = "bottom", gather = true},
			{map = "-28,-44", path = "right", gather = true},
			{map = "-27,-44", path = "bottom", gather = true},
			{map = "-27,-43", path = "bottom", gather = true},
			{map = "-26,-42", path = "right", gather = true},
			{map = "-27,-42", path = "bottom", gather = true},
			{map = "-26,-41", path = "top", gather = true},
			{map = "-25,-42", path = "top", gather = true},
			{map = "-25,-43", path = "top", gather = true},
			{map = "-25,-44", path = "right", gather = true},
			{map = "-22,-43", path = "bottom", gather = true},
			{map = "-23,-42", path = "bottom", gather = true},
			{map = "-23,-41", path = "right", gather = true},
			{map = "-22,-40", path = "left", gather = true},
			{map = "-24,-39", path = "bottom", gather = true},
			{map = "-26,-37", path = "left", gather = true},
			{map = "-27,-38", path = "left", gather = true},
			{map = "-28,-38", path = "bottom", gather = true},
			{map = "-28,-37", path = "left", gather = true},
			{map = "-29,-37", path = "top", gather = true},
			{map = "-29,-38", path = "top", gather = true},
			{map = "-29,-39", path = "right", gather = true},
			{map = "-28,-39", path = "right", gather = true},
			{map = "-28,-42", path = "top", gather = true},
			{map = "-27,-41", path = "right"},
			{map = "-24,-44", path = "right"},
			{map = "-23,-44", path = "right"},
			{map = "-22,-44", path = "bottom"},
			{map = "-22,-42", path = "left"},
			{map = "-22,-41", path = "bottom"},
			{map = "-23,-40", path = "left"},
			{map = "-24,-40", path = "bottom"},
			{map = "-24,-38", path = "bottom"},
			{map = "-24,-37", path = "left"},
			{map = "-25,-37", path = "left"},
			{map = "-27,-37", path = "top"},
			{map = "-27,-39", path = "top"},
			{map = "-27,-40", path = "left", gather = true},
			{map = "-28,-40", path = "top"},
			{map = "-28,-41", path = "top"},
			{map = "-28,-43", path = "left"},
			{map = "-29,-43", path = "top"},
			{map = "-29,-44", path = "top"},
			{map = "-30,-45", path = "right"},
			{map = "-30,-44", path = "right"},
			{map = "-30,-43", path = "right"},
			{map = "-30,-42", path = "right"},
			{map = "-29,-42", path = "right"},
			{map = "-30,-41", path = "right"},
			{map = "-29,-41", path = "right"},
			{map = "-29,-40", path = "right"},
			{map = "-30,-39", path = "right"},
			{map = "-30,-40", path = "right"},
			{map = "-30,-38", path = "right"},
			{map = "-30,-37", path = "right"},
			{map = "-21,-45", path = "left"},
			{map = "-21,-44", path = "left"},
			{map = "-21,-43", path = "left"},
			{map = "-21,-42", path = "left"},
			{map = "-21,-41", path = "left"},
			{map = "-21,-40", path = "left"},
			{map = "-21,-37", path = "left"},
			{map = "-21,-38", path = "left"},
			{map = "-21,-39", path = "left"},
			{map = "-22,-37", path = "left"},
			{map = "-22,-38", path = "left"},
			{map = "-22,-39", path = "left"},
			{map = "-23,-38", path = "left"},
			{map = "-23,-39", path = "left"},
			{map = "-23,-37", path = "left"},
			{map = "-22,-45", path = "left"},
			{map = "-23,-45", path = "left"},
			{map = "-24,-45", path = "left"},
			{map = "-25,-45", path = "left"},
			{map = "-26,-45", path = "left"},
			{map = "-27,-45", path = "left"},
			{map = "-26,-43", path = "left"},
			{map = "-26,-44", path = "left"},
			{map = "-23,-43", path = "left"},
			{map = "-24,-42", path = "left"},
			{map = "-24,-43", path = "left"},
			{map = "-25,-41", path = "left"},
			{map = "-24,-41", path = "left"},
			{map = "-25,-40", path = "left"},
			{map = "-26,-40", path = "left"},
			{map = "-26,-39", path = "left"},
			{map = "-25,-39", path = "left"},
			{map = "-25,-38", path = "left"},
			{map = "-26,-38", path = "left"},
		}
	elseif (job:level(28) >= 80) and (job:level(28) < 120) then
		GATHER = {39, 42, 45}
		return {
			{map = "2885641", path = "424"}, --Interieur banque Bonta vers Sortie--
			{map = "-32,-56", path = "bottom"},
			{map = "-32,-55", path = "bottom"},
			{map = "-32,-54", path = "right"},
			{map = "-31,-54", path = "right"},
			{map = "-30,-54", path = "right"},
			{map = "-29,-54", path = "bottom"},
			{map = "-29,-53", path = "bottom"},
			{map = "-29,-52", path = "bottom"},
			{map = "-29,-51", path = "bottom"},
			{map = "-29,-50", path = "bottom"},
			{map = "-29,-49", path = "bottom"},
			{map = "-29,-48", path = "bottom"},
			{map = "-29,-47", path = "bottom"},
			{map = "-29,-46", path = "bottom"},
			{map = "-29,-45", path = "bottom"},
			{map = "-29,-44", path = "right"},
			{map = "-28,-44", path = "right", gather = true},
			{map = "-27,-44", path = "bottom", gather = true},
			{map = "-27,-43", path = "left", gather = true},
			{map = "-28,-42", path = "right", gather = true},
			{map = "-27,-42", path = "bottom", gather = true},
			{map = "-27,-41", path = "right", gather = true},
			{map = "-26,-41", path = "top", gather = true},
			{map = "-26,-42", path = "right", gather = true},
			{map = "-25,-42", path = "right", gather = true},
			{map = "-23,-41", path = "right", gather = true},
			{map = "-22,-40", path = "bottom", gather = true},
			{map = "-23,-39", path = "top", gather = true},
			{map = "-24,-40", path = "bottom", gather = true},
			{map = "-24,-39", path = "left", gather = true},
			{map = "-25,-39", path = "left", gather = true},
			{map = "-26,-37", path = "left", gather = true},
			{map = "-27,-38", path = "top", gather = true},
			{map = "-27,-39", path = "left", gather = true},
			{map = "-28,-38", path = "bottom", gather = true},
			{map = "-28,-37", path = "left", gather = true},
			{map = "-29,-37", path = "top", gather = true},
			{map = "-29,-38", path = "top", gather = true},
			{map = "-28,-43", path = "bottom"},
			{map = "-24,-42", path = "bottom"},
			{map = "-24,-41", path = "right"},
			{map = "-22,-41", path = "bottom"},
			{map = "-22,-39", path = "left"},
			{map = "-23,-40", path = "left"},
			{map = "-26,-39", path = "bottom"},
			{map = "-26,-38", path = "bottom"},
			{map = "-27,-37", path = "top"},
			{map = "-28,-39", path = "bottom"},
			{map = "-29,-39", path = "top", gather = true},
			{map = "-29,-40", path = "right"},
			{map = "-28,-40", path = "top"},
			{map = "-28,-41", path = "left"},
			{map = "-29,-41", path = "top"},
			{map = "-29,-42", path = "top"},
			{map = "-29,-43", path = "top"},
			{map = "-30,-44", path = "right"},
			{map = "-30,-43", path = "right"},
			{map = "-30,-42", path = "right"},
			{map = "-30,-41", path = "right"},
			{map = "-30,-40", path = "right"},
			{map = "-30,-39", path = "right"},
			{map = "-30,-38", path = "right"},
			{map = "-30,-37", path = "right"},
			{map = "-21,-37", path = "left"},
			{map = "-21,-38", path = "left"},
			{map = "-21,-39", path = "left"},
			{map = "-21,-40", path = "left"},
			{map = "-21,-41", path = "left"},
			{map = "-21,-42", path = "left"},
			{map = "-21,-43", path = "left"},
			{map = "-21,-44", path = "left"},
			{map = "-22,-44", path = "left"},
			{map = "-22,-43", path = "left"},
			{map = "-22,-42", path = "left"},
			{map = "-23,-42", path = "left"},
			{map = "-23,-44", path = "left"},
			{map = "-23,-43", path = "left"},
			{map = "-24,-43", path = "left"},
			{map = "-24,-44", path = "left"},
			{map = "-25,-43", path = "left"},
			{map = "-25,-44", path = "left"},
			{map = "-26,-43", path = "left"},
			{map = "-26,-44", path = "left"},
			{map = "-22,-37", path = "left"},
			{map = "-22,-38", path = "left"},
			{map = "-23,-37", path = "left"},
			{map = "-23,-38", path = "left"},
			{map = "-24,-38", path = "left"},
			{map = "-24,-37", path = "left"},
			{map = "-25,-37", path = "left"},
			{map = "-25,-38", path = "left"},
			{map = "-25,-40", path = "left"},
			{map = "-25,-41", path = "left"},
			{map = "-26,-40", path = "left"},
			{map = "-27,-40", path = "left"},
		}
	elseif (job:level(28) >= 120) and (job:level(28) < 140) then
		GATHER = {39, 42, 45, 47}
		return {
			{map = "2885641", path = "424"}, --Interieur banque Bonta vers Sortie--
			{map = "-32,-56", path = "bottom"},
			{map = "-32,-55", path = "bottom"},
			{map = "-32,-54", path = "right"},
			{map = "-31,-54", path = "right"},
			{map = "-30,-54", path = "right"},
			{map = "-29,-54", path = "bottom"},
			{map = "-29,-53", path = "bottom"},
			{map = "-29,-52", path = "bottom"},
			{map = "-29,-51", path = "bottom"},
			{map = "-29,-50", path = "bottom"},
			{map = "-29,-49", path = "bottom"},
			{map = "-29,-48", path = "bottom"},
			{map = "-29,-47", path = "bottom"},
			{map = "-29,-46", path = "bottom"},
			{map = "-29,-45", path = "bottom"},
			{map = "-28,-42", path = "top", gather = true},
			{map = "-27,-43", path = "bottom", gather = true},
			{map = "-26,-42", path = "right", gather = true},
			{map = "-25,-42", path = "right", gather = true},
			{map = "-23,-41", path = "right", gather = true},
			{map = "-22,-40", path = "bottom", gather = true},
			{map = "-22,-39", path = "left", gather = true},
			{map = "-23,-39", path = "top", gather = true},
			{map = "-24,-40", path = "bottom", gather = true},
			{map = "-24,-39", path = "left", gather = true},
			{map = "-26,-40", path = "bottom", gather = true},
			{map = "-24,-42", path = "right"},
			{map = "-23,-42", path = "bottom"},
			{map = "-22,-41", path = "bottom"},
			{map = "-23,-40", path = "left"},
			{map = "-25,-39", path = "top", gather = true},
			{map = "-25,-40", path = "left"},
			{map = "-26,-39", path = "left"},
			{map = "-27,-40", path = "top"},
			{map = "-27,-41", path = "right", gather = true},
			{map = "-27,-42", path = "bottom", gather = true},
			{map = "-26,-41", path = "top", gather = true},
			{map = "-27,-44", path = "bottom", gather = true},
			{map = "-28,-44", path = "right", gather = true},
			{map = "-29,-44", path = "right"},
			{map = "-27,-39", path = "bottom", gather = true},
			{map = "-27,-38", path = "right", gather = true},
			{map = "-26,-37", path = "left", gather = true},
			{map = "-28,-37", path = "left", gather = true},
			{map = "-29,-37", path = "top", gather = true},
			{map = "-29,-38", path = "right", gather = true},
			{map = "-28,-38", path = "top", gather = true},
			{map = "-29,-39", path = "top", gather = true},
			{map = "-28,-41", path = "top"},
			{map = "-28,-43", path = "left"},
			{map = "-29,-43", path = "top"},
			{map = "-28,-40", path = "top"},
			{map = "-28,-39", path = "left"},
			{map = "-27,-37", path = "left"},
			{map = "-26,-38", path = "bottom"},
			{map = "-30,-44", path = "right"},
			{map = "-30,-43", path = "right"},
			{map = "-30,-42", path = "right"},
			{map = "-29,-40", path = "right"},
			{map = "-29,-41", path = "right"},
			{map = "-29,-42", path = "right"},
			{map = "-30,-41", path = "right"},
			{map = "-30,-40", path = "right"},
			{map = "-30,-38", path = "right"},
			{map = "-30,-39", path = "right"},
			{map = "-30,-37", path = "right"},
			{map = "-21,-37", path = "left"},
			{map = "-21,-38", path = "left"},
			{map = "-21,-39", path = "left"},
			{map = "-21,-40", path = "left"},
			{map = "-21,-41", path = "left"},
			{map = "-21,-42", path = "left"},
			{map = "-21,-44", path = "left"},
			{map = "-21,-43", path = "left"},
			{map = "-22,-44", path = "left"},
			{map = "-23,-44", path = "left"},
			{map = "-24,-44", path = "left"},
			{map = "-25,-44", path = "left"},
			{map = "-26,-44", path = "left"},
			{map = "-26,-43", path = "left"},
			{map = "-25,-43", path = "left"},
			{map = "-24,-43", path = "left"},
			{map = "-23,-43", path = "left"},
			{map = "-22,-43", path = "left"},
			{map = "-22,-42", path = "left"},
			{map = "-22,-38", path = "left"},
			{map = "-22,-37", path = "left"},
			{map = "-23,-37", path = "left"},
			{map = "-23,-38", path = "left"},
			{map = "-24,-38", path = "left"},
			{map = "-24,-37", path = "left"},
			{map = "-25,-37", path = "left"},
			{map = "-25,-38", path = "left"},
			{map = "-24,-41", path = "left"},
			{map = "-25,-41", path = "left"},
		}
	elseif (job:level(28) >= 140) and (job:level(28) <= 200) then
		GATHER = {39, 42, 45, 47, 46}
		return {
			{map = "2885641", path = "424"}, --Interieur banque Bonta vers Sortie--
			{map = "-32,-56", path = "bottom"},
			{map = "-32,-55", path = "bottom"},
			{map = "-32,-54", path = "right"},
			{map = "-31,-54", path = "right"},
			{map = "-30,-54", path = "right"},
			{map = "-29,-54", path = "bottom"},
			{map = "-29,-53", path = "bottom"},
			{map = "-29,-52", path = "bottom"},
			{map = "-29,-51", path = "bottom"},
			{map = "-29,-50", path = "bottom"},
			{map = "-29,-49", path = "bottom"},
			{map = "-29,-48", path = "bottom"},
			{map = "-29,-47", path = "bottom"},
			{map = "-29,-46", path = "bottom"},
			{map = "-29,-45", path = "bottom"},
			{map = "-28,-42", path = "top", gather = true},
			{map = "-27,-43", path = "bottom", gather = true},
			{map = "-26,-42", path = "right", gather = true},
			{map = "-25,-42", path = "right", gather = true},
			{map = "-23,-41", path = "right", gather = true},
			{map = "-22,-40", path = "bottom", gather = true},
			{map = "-22,-39", path = "left", gather = true},
			{map = "-23,-39", path = "top", gather = true},
			{map = "-24,-40", path = "bottom", gather = true},
			{map = "-24,-39", path = "left", gather = true},
			{map = "-26,-40", path = "bottom", gather = true},
			{map = "-24,-42", path = "right"},
			{map = "-22,-41", path = "bottom"},
			{map = "-23,-40", path = "left"},
			{map = "-25,-39", path = "top", gather = true},
			{map = "-26,-39", path = "left"},
			{map = "-27,-41", path = "right", gather = true},
			{map = "-27,-42", path = "bottom", gather = true},
			{map = "-26,-41", path = "top", gather = true},
			{map = "-28,-44", path = "right", gather = true},
			{map = "-29,-44", path = "right"},
			{map = "-27,-39", path = "bottom", gather = true},
			{map = "-27,-38", path = "right", gather = true},
			{map = "-26,-37", path = "left", gather = true},
			{map = "-28,-37", path = "left", gather = true},
			{map = "-29,-37", path = "top", gather = true},
			{map = "-29,-38", path = "right", gather = true},
			{map = "-28,-38", path = "top", gather = true},
			{map = "-29,-39", path = "top", gather = true},
			{map = "-28,-41", path = "top"},
			{map = "-28,-43", path = "left"},
			{map = "-29,-43", path = "top"},
			{map = "-28,-40", path = "top"},
			{map = "-28,-39", path = "left"},
			{map = "-27,-37", path = "left"},
			{map = "-26,-38", path = "bottom"},
			{map = "-29,-40", path = "right"},
			{map = "-27,-44", path = "right", gather = true},
			{map = "-26,-44", path = "bottom"},
			{map = "-26,-43", path = "left", gather = true},
			{map = "-23,-42", path = "bottom", gather = true},
			{map = "-25,-40", path = "left"},
			{map = "-21,-37", path = "left"},
			{map = "-21,-38", path = "left"},
			{map = "-22,-37", path = "left"},
			{map = "-23,-38", path = "left"},
			{map = "-22,-38", path = "left"},
			{map = "-23,-37", path = "left"},
			{map = "-24,-38", path = "left"},
			{map = "-24,-37", path = "left"},
			{map = "-25,-38", path = "left"},
			{map = "-25,-37", path = "left"},
			{map = "-21,-39", path = "left"},
			{map = "-21,-40", path = "left"},
			{map = "-21,-41", path = "left"},
			{map = "-21,-42", path = "left"},
			{map = "-21,-43", path = "left"},
			{map = "-21,-44", path = "left"},
			{map = "-22,-44", path = "left"},
			{map = "-22,-43", path = "left"},
			{map = "-23,-43", path = "left"},
			{map = "-23,-44", path = "left"},
			{map = "-24,-44", path = "left"},
			{map = "-24,-43", path = "left"},
			{map = "-25,-43", path = "left"},
			{map = "-25,-44", path = "left"},
			{map = "-22,-42", path = "left"},
			{map = "-24,-41", path = "left"},
			{map = "-25,-41", path = "left"},
			{map = "-27,-40", path = "left"},
			{map = "-30,-44", path = "right"},
			{map = "-30,-42", path = "right"},
			{map = "-30,-43", path = "right"},
			{map = "-30,-41", path = "right"},
			{map = "-30,-40", path = "right"},
			{map = "-30,-38", path = "right"},
			{map = "-30,-39", path = "right"},
			{map = "-30,-37", path = "right"},
		}
	end
end

function bank()
	return {
		{map = "-30,-40", path = "right"},
		{map = "-29,-40", path = "right"},
		{map = "-30,-39", path = "right"},
		{map = "-29,-39", path = "right"},
		{map = "-30,-38", path = "right"},
		{map = "-29,-38", path = "right"},
		{map = "-30,-41", path = "right"},
		{map = "-30,-42", path = "right"},
		{map = "-30,-43", path = "right"},
		{map = "-30,-44", path = "right"},
		{map = "-30,-45", path = "right"},
		{map = "-28,-38", path = "top"},
		{map = "-28,-39", path = "top"},
		{map = "-28,-40", path = "top"},
		{map = "-29,-41", path = "top"},
		{map = "-29,-42", path = "top"},
		{map = "-29,-43", path = "top"},
		{map = "-29,-44", path = "top"},
		{map = "-29,-45", path = "top"},
		{map = "-29,-46", path = "top"},
		{map = "-29,-47", path = "top"},
		{map = "-29,-48", path = "top"},
		{map = "-29,-49", path = "top"},
		{map = "-29,-50", path = "top"},
		{map = "-29,-51", path = "top"},
		{map = "-29,-52", path = "top"},
		{map = "-29,-53", path = "top"},
		{map = "-29,-54", path = "left"},
		{map = "-30,-54", path = "left"},
		{map = "-21,-44", path = "left"},
		{map = "-21,-43", path = "left"},
		{map = "-21,-42", path = "left"},
		{map = "-21,-41", path = "left"},
		{map = "-21,-40", path = "left"},
		{map = "-21,-39", path = "left"},
		{map = "-21,-38", path = "left"},
		{map = "-22,-38", path = "left"},
		{map = "-22,-39", path = "left"},
		{map = "-22,-40", path = "left"},
		{map = "-22,-41", path = "left"},
		{map = "-22,-43", path = "left"},
		{map = "-22,-44", path = "left"},
		{map = "-23,-44", path = "left"},
		{map = "-23,-43", path = "left"},
		{map = "-23,-42", path = "left"},
		{map = "-23,-41", path = "left"},
		{map = "-23,-40", path = "left"},
		{map = "-22,-42", path = "left"},
		{map = "-23,-39", path = "left"},
		{map = "-23,-38", path = "left"},
		{map = "-24,-38", path = "left"},
		{map = "-24,-39", path = "left"},
		{map = "-24,-40", path = "left"},
		{map = "-24,-42", path = "left"},
		{map = "-24,-43", path = "left"},
		{map = "-24,-44", path = "left"},
		{map = "-24,-41", path = "left"},
		{map = "-25,-43", path = "left"},
		{map = "-25,-44", path = "left"},
		{map = "-25,-41", path = "left"},
		{map = "-25,-42", path = "left"},
		{map = "-25,-40", path = "left"},
		{map = "-25,-39", path = "left"},
		{map = "-25,-38", path = "left"},
		{map = "-26,-38", path = "left"},
		{map = "-26,-39", path = "left"},
		{map = "-26,-40", path = "left"},
		{map = "-26,-41", path = "left"},
		{map = "-26,-42", path = "left"},
		{map = "-26,-43", path = "left"},
		{map = "-26,-44", path = "left"},
		{map = "-27,-44", path = "left"},
		{map = "-27,-43", path = "left"},
		{map = "-28,-43", path = "left"},
		{map = "-28,-44", path = "left"},
		{map = "-28,-42", path = "left"},
		{map = "-27,-42", path = "left"},
		{map = "-27,-41", path = "left"},
		{map = "-28,-41", path = "left"},
		{map = "-27,-39", path = "left"},
		{map = "-27,-40", path = "left"},
		{map = "-27,-38", path = "left"},
		{map = "-21,-45", path = "left"},
		{map = "-22,-45", path = "left"},
		{map = "-24,-45", path = "left"},
		{map = "-23,-45", path = "left"},
		{map = "-25,-45", path = "left"},
		{map = "-26,-45", path = "left"},
		{map = "-27,-45", path = "left"},
		{map = "-28,-45", path = "left"},
		{map = "-28,-37", path = "top"},
		{map = "-30,-37", path = "right"},
		{map = "-29,-37", path = "right"},
		{map = "-22,-37", path = "left"},
		{map = "-23,-37", path = "left"},
		{map = "-24,-37", path = "left"},
		{map = "-25,-37", path = "left"},
		{map = "-26,-37", path = "left"},
		{map = "-27,-37", path = "left"},
		{map = "-21,-37", path = "left"},
		{map = "147254", door = "383"}, --Devant banque Bonta--
		{map = "2885641", path = "424", npcBank = true}, --Banque Bonta--
	}
end