
-----------------------------------------------------------
-- This script is automatically generated by SnowFlake --
-- a script generator for snowbot developed by brizze.   --
-- https://www.snowbot.eu/ | https://dotrade.fr/accueil  --
--         Discord : https://discord.gg/9qF34VW          --
-----------------------------------------------------------

AUTO_DELETE = {}         -- Add the identifiers of the objects you want to delete (CF : https://www.snowbot.eu/objets.txt)
GATHER = {}              -- Add the identifiers of the resources you want to harvest (CF : https://www.snowbot.eu/ressources.txt)
MIN_MONSTERS = 1         -- Change the minimum number of monsters the bot will fight
MAX_MONSTERS = 1         -- Change the maximum number of monsters the bot will fight
OPEN_BAGS = true       -- Change the parameter to true to automatically open the harvest bags
FORBIDDEN_MONSTERS = {}  -- You can define the banned monsters in a group to fight. (CF : https://www.snowbot.eu/monstres.txt)
FORCE_MONSTERS = {}      -- You can define the mandatory monsters in a group to fight. (CF : https://www.snowbot.eu/monstres.txt)

function move()
    return {
   { map = "-16,1", path = "bottom", gather = true, fight = false },  
   { map = "-16,2", path = "bottom", gather = true, fight = false },  
   { map = "73400323", path = "right", gather = true, fight = false },  
   { map = "84935175", path = "425" },  
   { map = "-16,3", path = "bottom", gather = true, fight = false },  
   { map = "-15,4", path = "right", gather = true, fight = false },  
   { map = "-14,4", path = "right", gather = true, fight = false },  
   { map = "-13,4", path = "right", gather = true, fight = false },  
   { map = "-12,4", path = "right", gather = true, fight = false },  
   { map = "-11,4", path = "bottom", gather = true, fight = false },  
   { map = "-11,5", path = "bottom", gather = true, fight = false },  
   { map = "-11,6", path = "bottom", gather = true, fight = false },  
   { map = "-11,7", path = "bottom", gather = true, fight = false },  
   { map = "-11,8", path = "bottom", gather = true, fight = false },  
   { map = "-11,9", path = "bottom", gather = true, fight = false },  
   { map = "-11,10", path = "bottom", gather = true, fight = false },  
   { map = "-11,11", path = "bottom", gather = true, fight = false },  
   { map = "-11,12", path = "right", gather = true, fight = false },  
   { map = "-10,12", path = "right", gather = true, fight = false },  
   { map = "-9,12", path = "bottom", gather = true, fight = false },  
   { map = "-9,13", path = "bottom", gather = true, fight = false },  
   { map = "-9,14", path = "right", gather = true, fight = false },  
   { map = "-8,14", path = "right", gather = true, fight = false },  
   { map = "-7,14", path = "right", gather = true, fight = false },  
   { map = "-6,14", path = "top", gather = true, fight = false },  
   { map = "-7,13", path = "top", gather = true, fight = false },  
   { map = "-8,12", path = "top", gather = true, fight = false },  
   { map = "-6,13", path = "left", gather = true, fight = false },  
   { map = "-7,12", path = "left", gather = true, fight = false },  
   { map = "-8,11", path = "left", gather = true, fight = false },  
   { map = "-9,11", path = "left", gather = true, fight = false },  
   { map = "-8,9", path = "left", gather = true, fight = false },  
   { map = "-9,9", path = "left", gather = true, fight = false },  
   { map = "-10,11", path = "top", gather = true, fight = false },  
   { map = "-8,10", path = "top", gather = true, fight = false },  
   { map = "-10,9", path = "top", gather = true, fight = false },  
   { map = "-10,8", path = "top", gather = true, fight = false },  
   { map = "-10,7", path = "top", gather = true, fight = false },  
   { map = "-10,6", path = "top", gather = true, fight = false },  
   { map = "-10,5", path = "top", gather = true, fight = false },  
   { map = "-10,10", path = "right", gather = true, fight = false },  
   { map = "-9,10", path = "right", gather = true, fight = false },  
   { map = "-10,4", path = "left", gather = true, fight = false },  
   }
end


function bank()
    return {
		{ map = "0,0", path = "zaap(73400320)"},
		{ map:currentMapId(), path = "havenbag" },
		{ map = "-16,1", path = "bottom" },  
		{ map = "-16,2", path = "bottom" },
		{ map = "73400323", door = "330" },  
		{ map = "84935175", path = "425", npcBank = true },  
   }
end

function phenix()
    return {
   }
end

