
-----------------------------------------------------------
-- This script is automatically generated by SnowFlake --
-- a script generator for snowbot developed by brizze.   --
-- https://www.snowbot.eu/ | https://dotrade.fr/accueil  --
--         Discord : https://discord.gg/9qF34VW          --
-----------------------------------------------------------

AUTO_DELETE = {}         -- Add the identifiers of the objects you want to delete (CF : https://www.snowbot.eu/objets.txt)
GATHER = {}              -- Add the identifiers of the resources you want to harvest (CF : https://www.snowbot.eu/ressources.txt)
MIN_MONSTERS = 1         -- Change the minimum number of monsters the bot will fight
MAX_MONSTERS = 8         -- Change the maximum number of monsters the bot will fight
OPEN_BAGS = true        -- Change the parameter to true to automatically open the harvest bags
FORBIDDEN_MONSTERS = {}  -- You can define the banned monsters in a group to fight. (CF : https://www.snowbot.eu/monstres.txt)
FORCE_MONSTERS = {}      -- You can define the mandatory monsters in a group to fight. (CF : https://www.snowbot.eu/monstres.txt)

function move()
    return {
	{ map = map:currentMapId(), path = "havenbag" },
	{ map = "0,0", path = "zaap(147590153)"},
   { map = "-17,-47", path = "bottom", gather = true, fight = false },  
   { map = "-17,-46", path = "bottom", gather = true, fight = false },  
   { map = "-13,-45", path = "bottom", gather = true, fight = false },  
   { map = "-13,-44", path = "bottom", gather = true, fight = false },  
   { map = "-13,-43", path = "bottom", gather = true, fight = false },  
   { map = "-11,-45", path = "bottom", gather = true, fight = false },  
   { map = "-11,-44", path = "bottom", gather = true, fight = false },  
   { map = "-11,-43", path = "bottom", gather = true, fight = false },  
   { map = "-13,-42", path = "right", gather = true, fight = false },  
   { map = "-11,-42", path = "right", gather = true, fight = false },  
   { map = "-10,-42", path = "right", gather = true, fight = false },  
   { map = "-12,-42", path = "top", gather = true, fight = false },  
   { map = "-12,-43", path = "top", gather = true, fight = false },  
   { map = "-12,-44", path = "top", gather = true, fight = false },  
   { map = "-9,-42", path = "top", gather = true, fight = false },  
   { map = "-9,-43", path = "top", gather = true, fight = false },  
   { map = "-9,-44", path = "top", gather = true, fight = false },  
   { map = "-9,-45", path = "left", gather = true, fight = false },  
   { map = "-17,-45", path = "right", gather = true, fight = false },  
   { map = "-16,-45", path = "right", gather = true, fight = false },  
   { map = "-15,-45", path = "right", gather = true, fight = false },  
   { map = "-14,-45", path = "right", gather = true, fight = false },  
   { map = "-10,-45", path = "top", gather = true, fight = false },  
   { map = "-10,-46", path = "left", gather = true, fight = false },  
   { map = "-11,-46", path = "left", gather = true, fight = false },  
   { map = "-12,-46", path = "left", gather = true, fight = false },  
   { map = "-13,-46", path = "bottom", gather = true, fight = false },  
   }
end


function bank()
    return {
	{ map = "0,0", path = "zaap(147768)"},
	{ map= map:currentMapId(), path = "havenbag" },
   { map = "-32,-56", path = "right" },  
   { map = "-31,-56", path = "bottom" },  
   { map = "-31,-55", path = "bottom" },  
   {map = "2885641", path = "424", npcBank = true}, --Interieur banque Bonta vidage items--
	{map = "147254", door = "383" },
   }
end


	

function phenix()
    return {
   }
end
